package com.oakinvest.lt.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 * User.
 */
@DynamoDBTable(tableName = "USERS")
public class User {

    /**
     * ID.
     */
    private String id;

    /**
     * First name.
     */
    private String firstName;

    /**
     * Last name.
     */
    private String lastName;

    /**
     * Email.
     */
    private String email;

    /**
     * Google username retrieved when signed up with google.
     */
    private String googleUsername;

    /**
     * Default constructor.
     */
    public User() {
    }

    /**
     * Constructor.
     *
     * @param newFirstName first name
     * @param newLastName  last name
     * @param newEmail     email
     */
    public User(final String newFirstName, final String newLastName, final String newEmail) {
        this.firstName = newFirstName;
        this.lastName = newLastName;
        this.email = newEmail;
        this.googleUsername = newEmail;
    }

    /**
     * Get id.
     *
     * @return id
     */
    @DynamoDBHashKey(attributeName = "ID")
    @DynamoDBAutoGeneratedKey
    public final String getId() {
        return id;
    }

    /**
     * Set id.
     *
     * @param newId the id to set
     */
    public final void setId(final String newId) {
        id = newId;
    }

    /**
     * Get firstName.
     *
     * @return firstName
     */
    @DynamoDBAttribute(attributeName = "FIRST_NAME")
    public final String getFirstName() {
        return firstName;
    }

    /**
     * Set firstName.
     *
     * @param newFirstName the firstName to set
     */
    public final void setFirstName(final String newFirstName) {
        firstName = newFirstName;
    }

    /**
     * Get lastName.
     *
     * @return lastName
     */
    @DynamoDBAttribute(attributeName = "LAST_NAME")
    public final String getLastName() {
        return lastName;
    }

    /**
     * Set lastName.
     *
     * @param newLastName the lastName to set
     */
    public final void setLastName(final String newLastName) {
        lastName = newLastName;
    }

    /**
     * Get email.
     *
     * @return email
     */
    @DynamoDBAttribute(attributeName = "EMAIL")
    public final String getEmail() {
        return email;
    }

    /**
     * Set email.
     *
     * @param newEmail the email to set
     */
    public final void setEmail(final String newEmail) {
        email = newEmail;
    }

    /**
     * Get googleUsername.
     *
     * @return googleUsername
     */
    @DynamoDBIndexHashKey(attributeName = "GOOGLE_USERNAME", globalSecondaryIndexName = "INDEX_GOOGLE_USERNAME")
    public final String getGoogleUsername() {
        return googleUsername;
    }

    /**
     * Set googleUsername.
     *
     * @param newGoogleUserName the googleUsername to set
     */
    public final void setGoogleUsername(final String newGoogleUserName) {
        googleUsername = newGoogleUserName;
    }

}
