package com.oakinvest.lt.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.oakinvest.lt.authentication.loosetouch.AccountAuthentication;

import static com.oakinvest.lt.authentication.loosetouch.AccountAuthentication.GOOGLE;

/**
 * Account.
 */
@SuppressWarnings("unused")
@DynamoDBTable(tableName = "ACCOUNTS")
public class Account {

    /**
     * ID.
     */
    @DynamoDBHashKey(attributeName = "ID")
    @DynamoDBAutoGeneratedKey
    private String id;

    /**
     * First name.
     */
    @DynamoDBAttribute(attributeName = "FIRST_NAME")
    private String firstName;

    /**
     * Last name.
     */
    @DynamoDBAttribute(attributeName = "LAST_NAME")
    private String lastName;

    /**
     * Email.
     */
    @DynamoDBAttribute(attributeName = "EMAIL")
    private String email;

    /**
     * Profile image url.
     */
    @DynamoDBAttribute(attributeName = "PICTURE_URL")
    private String pictureUrl;

    /**
     * Google username retrieved when signed up with google.
     */
    @DynamoDBIndexHashKey(attributeName = "GOOGLE_USERNAME", globalSecondaryIndexName = "INDEX_GOOGLE_USERNAME")
    private String googleUsername;

    /**
     * Default constructor.
     */
    public Account() {
    }

    /**
     * Constructor.
     *
     * @param newFirstName       first name
     * @param newLastName        last name
     * @param newEmail           email
     * @param newImageUrl        image url
     * @param accountAuthentication account authentication (google)
     */
    public Account(final String newFirstName, final String newLastName, final String newEmail, final String newImageUrl, final AccountAuthentication accountAuthentication) {
        this.firstName = newFirstName;
        this.lastName = newLastName;
        this.email = newEmail;
        this.pictureUrl = newImageUrl;

        // Authentication type GOOGLE.
        if (accountAuthentication == GOOGLE) {
            this.googleUsername = newEmail;
        }
    }

    /**
     * Get id.
     *
     * @return id
     */
    public final String getId() {
        return id;
    }

    /**
     * Set id.
     *
     * @param newId the id to set
     */
    public final void setId(final String newId) {
        id = newId;
    }

    /**
     * Get firstName.
     *
     * @return firstName
     */
    public final String getFirstName() {
        return firstName;
    }

    /**
     * Set firstName.
     *
     * @param newFirstName the firstName to set
     */
    public final void setFirstName(final String newFirstName) {
        firstName = newFirstName;
    }

    /**
     * Get lastName.
     *
     * @return lastName
     */
    public final String getLastName() {
        return lastName;
    }

    /**
     * Set lastName.
     *
     * @param newLastName the lastName to set
     */
    public final void setLastName(final String newLastName) {
        lastName = newLastName;
    }

    /**
     * Get email.
     *
     * @return email
     */
    public final String getEmail() {
        return email;
    }

    /**
     * Set email.
     *
     * @param newEmail the email to set
     */
    public final void setEmail(final String newEmail) {
        email = newEmail;
    }

    /**
     * Get pictureUrl.
     *
     * @return pictureUrl
     */
    public final String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * Set pictureUrl.
     *
     * @param newImageUrl the pictureUrl to set
     */
    public final void setPictureUrl(final String newImageUrl) {
        pictureUrl = newImageUrl;
    }

    /**
     * Get googleUsername.
     *
     * @return googleUsername
     */
    public final String getGoogleUsername() {
        return googleUsername;
    }

    /**
     * Set googleUsername.
     *
     * @param newGoogleUserName the googleUsername to set
     */
    public final void setGoogleUsername(final String newGoogleUserName) {
        googleUsername = newGoogleUserName;
    }

}
